// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var UnistUtilVisit = require("unist-util-visit");
var Curlie$GatsbyRemarkCurlie = require("./Curlie.bs.js");

var MappingNotFound = Caml_exceptions.create("RemarkCurlie-GatsbyRemarkCurlie.MappingNotFound");

function toMapping(record) {
  return /* record */[
          /* prefix */record.id,
          /* url */record.url
        ];
}

function bibToString(record) {
  var id = record.id;
  var title = record.title;
  var publisher = record.publisher;
  var published = record.published;
  var joinAuthors = function (authors) {
    if (authors !== undefined) {
      var authors$1 = authors;
      if (authors$1.length === 0) {
        return undefined;
      } else {
        return authors$1.reduce((function (acc, value) {
                      return acc + (", " + value);
                    }), "");
      }
    }
    
  };
  var authors = joinAuthors(record.authors);
  return /* array */[
            title,
            authors,
            published,
            publisher
          ].reduce((function (acc, value) {
                if (value !== undefined) {
                  return acc + (" " + (value + "."));
                } else {
                  return acc;
                }
              }), "[" + (id + "]"));
}

function $$default(ast, config) {
  var db = config.db;
  var mappings = $$Array.to_list(db.map(toMapping));
  var visitor = function (node) {
    var href = node.url;
    var curlie = Curlie$GatsbyRemarkCurlie.fromString(href);
    if (curlie !== undefined) {
      var curlie$1 = curlie;
      var match = Curlie$GatsbyRemarkCurlie.expand(curlie$1, mappings);
      if (match !== undefined) {
        var prefix = curlie$1[0];
        var bib = Belt_Option.getWithDefault(Belt_Option.map(Js_primitive.undefined_to_opt(db.find((function (record) {
                            return record.id === prefix;
                          }))), bibToString), "");
        node.url = match;
        node.title = bib;
        return /* () */0;
      } else {
        throw [
              MappingNotFound,
              "Found a curlie " + (href + " without an entry in the catalogue.")
            ];
      }
    } else {
      return /* () */0;
    }
  };
  UnistUtilVisit(ast, "link", visitor);
  return ast;
}

exports.MappingNotFound = MappingNotFound;
exports.toMapping = toMapping;
exports.bibToString = bibToString;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* unist-util-visit Not a pure module */
